config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'staticpages#home'
  get '/top' => 'songs#top'

  root 'staticpages#home'

 resources :artists, :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs, dependent: :destroy
	validates :name, presence: true
	validates :name, uniqueness: true

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def star_rating
  	rating || 0  	
  end

  def average_rating
  	Song.where(artist_id: self.id).average("rating").to_i || 0  	
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :artist
	validates :name, :rating, :artist_id, presence: true
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	
	def index
		@artists = Artist.all
		@songs = Song.all
	end

	def new
		@artist = Artist.new
	end

	def edit
		
	end

	def show
		@spotify_artist = RSpotify::Artist.search(artist.name).first
		@spotify_playlists = RSpotify::Playlist.search(artist.name).take(5)
		@songs = Song.where(artist_id: artist.id)
	end

	def update
		artist.update(artist_params)
		
		if artist.save
			flash[:success] = "Artist updated successfully."
			redirect_to :artists => "show"
		else
			flash[:error] = "Your updates were not saved."
			redirect_to :artists => "edit"
		end
	end

	def create
		@artist = Artist.new(artist_params)
		@artist.save

		if @artist.save
			flash[:success] = "Artist created successfully."
			redirect_to :artists => 'show'
		else
			flash[:error] = "There was an error creating this artist."
			redirect_to :artists => "edit"
		end
	end

	def destroy
		artist.destroy

		redirect_to :action => "index"		
	end
	
	private

	def artist
		@artist ||= Artist.find(params[:id])
	end
	helper_method :artist

	def artist_params
		params.require(:artist).permit(:name, :rating, :image)		
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def index
		@songs = Song.all
	end

	def new
		@song = Song.new
		@artists = Artist.all
	end

	def create
		@song = Song.create(song_params)

		if @song.save
			flash[:success] = "Song created successfully."
			redirect_to :songs => 'show'
		else
			flash[:error] = "There was an error creating this song."
			redirect_to :songs => "edit"
		end
	end

	def show

	end

	def edit
		@artists = Artist.all
	end

	def update
		song.update(song_params)
		
		if song.save
			flash[:success] = "Song updated successfully."
			redirect_to :songs => "show"
		else
			flash[:error] = "Your updates were not saved."
			redirect_to :songs => "edit"
		end
	end

	def destroy
		song.destroy

		redirect_to :action => "index"
	end

	def top
		@top_songs = Song.all.order('rating DESC').take(5)
	end

	private

	def song
		@song ||= Song.find(params[:id])
	end
	helper_method :song

	def song_params
		params.require(:song).permit(:name, :rating, :artist_id)
	end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/artists/_form.html.erb
<%= form_for artist, html: {multipart: true } do |f| %>
	
		<div class="form-field">
			<%= f.text_field :name, :placeholder => "Name", class: "form-control" %>
		</div>

	<br>

	<div class="form-field">
		<%= f.label "Add an image:" %>
		<%= f.file_field :image, class: "form-control" %>
	</div>

	<div class="form-field">
		<%= f.submit "Save", class: "btn btn-primary" %>
	</div>

<% end %>

app/views/artists/edit.html.erb
<div class="container-fluid">
<h1>Edit Artist</h1>

	<%= render 'form' %>
</div>

app/views/artists/index.html.erb
<div class="container-fluid">

<div class="container">
	<%= link_to new_artist_path, class: "btn btn-primary btn-top" do %>
	    <i class="glyphicon glyphicon-plus-sign"></i> Add A New Artist
	<% end %>
</div>

	<div class="tiles">
		<% @artists.each do |artist| %>
			<div class="well">
				<p><%= link_to image_tag(artist.image.url(:thumb), class: "img-circle"), artist %></p>
					<%= link_to artist.name, artist_path(artist) %>
					<br>
					<br>
					<div class="text-center">
						<% if artist.average_rating == 0 %>
						This artist is currently unrated.
						<% else %>
						<% artist.average_rating.times do %>
							<span class="glyphicon glyphicon-star"></span>
						<% end %>
					<br>
					(<%= artist.average_rating %>/10)
				<% end %>
					</div>
				<hr>
				<div>
					<%= link_to edit_artist_path(artist), class: "btn btn-primary btn-top" do %>
			    <i class="glyphicon glyphicon-pencil"></i> Edit Artist
					<% end %>
					<%= link_to artist_path(artist), method: :delete, class: "btn btn-primary btn-top", data: { confirm: "Do you really want to delete this artist along with all of their songs?" } do %>
			    <i class="glyphicon glyphicon-trash"></i> Delete Artist
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/artists/new.html.erb
<div class="container-fluid form">
<h1>New Artist</h1>

	<%= render 'form' %>
</div>

app/views/artists/show.html.erb
<div class="container show col-sm-7 col-lg-7">
	<h1><strong><%= artist.name %></strong></h1>

	<h3>Average Rating: 
		<br>
		<% artist.average_rating.times do %>
		<span class="glyphicon glyphicon-star"></span>
		<% end %> (<%= artist.average_rating %>/10)
	</h3>
	<hr>

	<h2>Songs by this artists:</h2>
	<% @songs.each do |song| %>
	<h3><%= link_to song.name, song %></h3>
	<% end %>
</div>


<div class="container show col-sm-4 col-lg-4">
	<h1><strong>You may also like:</h1></strong>
	<% @spotify_artist.related_artists.take(12).each do |spotify_artist| %>
		<p><%= link_to spotify_artist.name, spotify_artist.uri %></p>
	<% end %>
</div>


<div class="container show col-sm-4 col-lg-4">
	<h1><strong>Playlists you may like:</h1></strong>
	<% @spotify_playlists.each do |spotify_playlist| %>
			<p><%= link_to spotify_playlist.name, spotify_playlist.uri(country: "US") %></p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMDb | Internet Music Database</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
</head>
<body>
	
	<nav class="navbar navbar-default" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "IMDb - Internet Music Database", root_path, class: "navbar-brand" %>
		</div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Top 5", top_path %></li>
				<li><%= link_to "All Artists", artists_path %></li>
				<li><%= link_to	"All Songs", songs_path %></li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</nav>

<div class="container">
 <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
 </div>

<%= yield %>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for song do |f| %>

	<div class="form-field">
		<%= f.text_field :name, :placeholder => "Name", class: "form-control" %>
	</div>

		<br>
	
	<div class="form-field">
		<%= f.collection_select( :artist_id, @artists, :id, :name, {prompt: "Select an artist:"}, class: "form-control")%>
	</div>

		<br>

	<div class="form-field">
		<%= f.select :rating, (1..10), {prompt: "Rating"}, class: "form-control" %>
	</div>

	<br>

	<div class="form-field">
		<%= f.submit "Save", class: "btn btn-primary" %>
	</div>

<% end %>

app/views/songs/edit.html.erb
<div class="container-fluid form">
<h1>Edit Song</h1>

	<%= render 'form' %>
</div>

app/views/songs/index.html.erb
<div class="container-fluid">

<div class="container">
	<%= link_to new_song_path, class: "btn btn-primary btn-top" do %>
	    <i class="glyphicon glyphicon-plus-sign"></i> Add A New Song
	<% end %>
</div>

	<div class="tiles">
		<% @songs.each do |song| %>
			<div class="well">
					<p><%= link_to song.name, song_path(song) %></p>
					<p>by <%= link_to song.artist.name, artist_path(song.artist_id) %></p>
					<p>	<% song.rating.times do %>
							<span class="glyphicon glyphicon-star"></span>
							<% end %>
					<br>
					(<%= song.rating %>/10)
					</p>
				<hr>
				<div>
					<%= link_to edit_song_path(song), class: "btn btn-primary btn-top" do %>
			    <i class="glyphicon glyphicon-pencil"></i> Edit Song
					<% end %>
					<%= link_to song_path(song), method: :delete, class: "btn btn-primary btn-top", data: { confirm: "Do you really want to delete this song?" } do %>
			    <i class="glyphicon glyphicon-trash"></i> Delete Song
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/songs/new.html.erb
<div class="container-fluid form">

		<h1>New Song</h1>

		<%= render 'form' %>

</div>

app/views/songs/show.html.erb
<div class="container show">
	<h1><%= song.name %></h1>
	<h1>by <%= link_to song.artist.name, artist_path(song.artist_id) %></h1>
	<hr>
	<h2>Rating: 
		<% song.rating.times do %>
		<span class="glyphicon glyphicon-star"></span>
		<% end %>
		(<%= song.rating %>/10)
	</h2>
</div>

app/views/songs/top.html.erb
<div class="container-fluid">
<h1>Top 5 Songs</h1>

<div class="tiles">
		<% @top_songs.each do |song| %>
			<div class="well">
				<p><%= link_to image_tag(song.artist.image.url(:thumb), class: "img-circle"), artist_path(song.artist_id) %></p>
					<p><%= link_to song.name, song %></p>
					<p>by <%= link_to song.artist.name, artist_path(song.artist_id) %></p>
				<hr>
				<p><% song.rating.times do %>
					<span class="glyphicon glyphicon-star"></span>
				<% end %>
				</p>
				<p><%= song.rating %></p>
			</div>
		<% end %>
	</div>
</div>

app/views/staticpages/home.html.erb
<div class="jumbotron">
	<h1> Your music. Classified.</h1>
	<%= link_to "All Artists", artists_path, class: "btn btn-primary btn-lg" %>
	<%= link_to "Top 5 Songs", top_path, class: "btn btn-primary btn-lg" %>

</div>